var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];
const commentsList = [
  "This video is amazing!",
  "I can't believe how much I learned from this",
  "Great job! Keep up the good work",
  "Wow, I never knew that before",
  "Awesome tutorial, thanks!",
  "This is exactly what I was looking for",
  "I'm so glad I found this video",
  "This is the best explanation I've seen so far",
  "Thank you so much for sharing this",
  "This helped me so much with my project",
  "I can't wait to try this out",
  "I've been struggling with this for so long, thank you!",
  "You're a lifesaver!",
  "This is so well-explained, thank you",
  "You're a great teacher",
  "I've watched this video five times and I still love it",
  "This is the best channel on YouTube",
  "This deserves a million views",
  "I wish I had found this sooner",
  "You make it look so easy",
  "I love your energy and enthusiasm",
  "You have a new subscriber!",
  "This is better than any paid course I've taken",
  "I'm blown away by your knowledge",
  "This is a game-changer for me",
  "I'm going to recommend this to all my friends",
  "I'm so grateful for this video",
  "I can't believe this is free!",
  "I'm going to watch all your videos now",
  "This video is a work of art",
  "I wish I could give this a million likes",
  "This is the gold standard for tutorials",
  "You've made my day with this video",
  "I'm so inspired by this",
  "I'm going to share this with my entire team",
  "This is a masterpiece",
  "You're a genius",
  "This is the best thing I've seen all week",
  "You're changing lives with your content",
  "I can't thank you enough for this",
  "This is exactly what I needed to see today",
  "I'm blown away by your expertise",
  "I can't wait to see what you do next",
  "I'm going to watch this again and again",
  "This video is a game-changer",
  "You're making a real difference in people's lives",
  "I'm so glad I stumbled upon this",
  "This is so helpful, thank you",
  "You have a real talent for explaining things",
  "I'm in awe of your skills",
  "This is the kind of content that makes YouTube great",
  "I've learned more from this video than from a semester of classes",
  "I've never seen anyone explain this so well",
  "You have a gift for teaching",
  "This is the most useful video I've ever seen",
  "I'm amazed by your creativity",
  "You've inspired me to try something new",
  "I can't believe how much I've learned in just a few minutes",
  "This is a game-changer for my business",
  "I'm going to implement this right away",
  "You're a true expert in your field",
  "This video is a treasure trove of information",
  "You're making the world a better place with your content",
  "I'm going to watch this with my entire team",
  "You're a real asset",
];
export function generateName() {
  let finalName = nameList[Math.floor(Math.random() * nameList.length)];
  return finalName;
}

export function generateComment() {
  let finalComment =
    commentsList[Math.floor(Math.random() * commentsList.length)];
  return finalComment;
}
